minicpm-embedding-light:
  model_id: OpenBMB/MiniCPM-Embedding-Light
  model_type: embedding


minicpm-reranker-light:
  model_id: OpenBMB/MiniCPM-Reranker-Light
  model_type: reranker

Qwen2.5-14B-Instruct:
  model_id: Qwen/Qwen2.5-14B-Instruct
  model_type: llm

